[workspace]
preview=["pixi-build"]
description = "OpenGL bindings for mojo"
authors = ["Slava Chaunin <67190162+Ssslakter@users.noreply.github.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
platforms = ["linux-64"]

[package]
name = "opengl-mojo"
version = "0.0.4"
license-file = "LICENSE"
authors.workspace = true

[package.build.backend]
name="pixi-build-mojo"
version = "0.1.*"

[package.build.config.pkg]
name = "opengl"

[package.host-dependencies]
mojo-compiler = "0.25.7.*"

[package.build-dependencies]
mojo-compiler = "0.25.7.*"

[package.run-dependencies]
mojo-compiler = "0.25.7.*"

[tasks]
fmt = "mojo format -l 1000 src"
gen = "python gen.py"
pkg = "mojo package src -o opengl.mojopkg"
build = {depends-on = ["gen", "fmt", "pkg"]}
setup = {cmd = "./examples/init.sh"}
example = {cmd = "mojo run examples/hello.mojo"}

[dependencies]
mojo = "0.25.7.*"
libopengl = ">=1.7.0,<2"

[feature.dev.pypi-dependencies]
ipython = "*"
ipykernel = ">=6.29.5, <7"

[feature.dev.dependencies]
sdl3 = ">=3.2.16,<4"
python = ">=3.13.5,<3.14"
llvm-tools = ">=20.1.5,<21"

[environments]
dev = ['dev']
